### ISSUE TITLE
Relecture rapide

### ISSUE THREAD

**Issue by giliam** [flotpython/webintro#1]
Merci Thierry ! J'ai commencé à relire, sans trop réfléchir sur le fond de ce qui est dit (qui me semble d'ailleurs très bien !) sauf quand ça me surprend !

* notebook 11 : 
  - slide 7 : le code python de la cellule reste présent...
  - slide 10 : styling tags. A mon humble avis, ce ne sont pas des styling tags même s'ils le permettent. Mais plutôt des tags sémantiques disant, pour `<b>` par exemple, qu'un élément est important (comme` tout le reste d'HTML mais tu le mentionnes peut-être plus tard ?). Sauf si tu n'as pas choisi d'enseigner le HTML comme un langage portant une sémantique !
   - slide 11 : il y a un `\` en trop à la fin de la première ligne
   - slide 12 : `div` et `span` sont pareils mais span est pour un contenu _inline_ et div pour des _blocks_, non ? Cela ne vaut peut-être pas le coup d'introduire tout de suite cette distinction.
* notebook 13 : 
   - slide 5 : _which means it can be fetched anywhere with http_ -> _which means it can fetch any address through http_ ? Je ne comprends pas :D
   - slide 6 : le dernier retour à la ligne entre la puce 3 et 4 n'est pas superbe !

Je continue plus tard !

**Comment by giliam** [comment]
Notebook 14

- slide 5 : tu ne mentionnes pas (même si cela peut paraître évident) qu'un tag peut avoir plusieurs class dans son attribut en les séparant par des espaces.
- slide 8 : _maunally_ -> _manually_

**Comment by parmentelat** [comment]
Hey Matthieu

merci pour ces commentaires; j'ai pris en compte les plus faciles

* nb11/sl10: voui bon on va pas chipoter; je ne suis pas trop d'accord, disons que `<section>` et `<article>` je comprendrais, mais `<b>` par exemple c'est juste un bidule qui traine parce qu'il est là depuis toujours mais on aurait pu le faire avec une classe `span.bold` en une seul règle, et c'est plutôt comme ça qu'il faut le voir AMHA; 
* nb11/sl11: je suis d'accord mais je ne sais pas le corriger à ce stade, peut-être plus tard; le notebook est OK en ce sens que le texte est OK mais la macro qui le met en page est buggée, je verrai si j'ai le temps de l'arranger
* nb11/sl12 je suis d'accord, c'est la même remarque qu'avec `<b>` un peu..
* nb13/sl5: j'ai légèrement rephrasé, mais je ne suis pas sûr d'avoir compris ton point
* nb13/sl6: pas vu le souci ??

et ps le code des notebooks n'est pas du python mais .. du javascript, bien sûr !

merci en tous cas de ta relecture !

**Comment by giliam** [comment]
- ok !
- ok !
- ok !
- ok !
- rien, parfois, le format de puces fait que les retours à de nouvelles ne sont pas du tout naturels et arrivent en plein milieu de phrase. C'est peut-être juste moi qui continue à être mal à l'aise avec ces slides.
